name: Stock Alert

on:
  schedule:
    - cron: '* * * * *'

  workflow_dispatch:

jobs:
  monitor:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install requests

      - run: python stock.py
        env:
          FINNHUB_KEY: ${{ secrets.FINNHUB_KEY }}
          DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
